package com.cs.crm.settings.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.id
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.deptId
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.loginAct
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String loginact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.name
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.loginPwd
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String loginpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.email
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.expireTime
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String expiretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.lockStatus
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String lockstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.allowIps
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String allowips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.createBy
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.createTime
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.editBy
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String editby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.editTime
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    private String edittime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.id
     *
     * @return the value of tbl_user.id
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.id
     *
     * @param id the value for tbl_user.id
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.deptId
     *
     * @return the value of tbl_user.deptId
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.deptId
     *
     * @param deptid the value for tbl_user.deptId
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.loginAct
     *
     * @return the value of tbl_user.loginAct
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getLoginact() {
        return loginact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.loginAct
     *
     * @param loginact the value for tbl_user.loginAct
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setLoginact(String loginact) {
        this.loginact = loginact == null ? null : loginact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.name
     *
     * @return the value of tbl_user.name
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.name
     *
     * @param name the value for tbl_user.name
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.loginPwd
     *
     * @return the value of tbl_user.loginPwd
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.loginPwd
     *
     * @param loginpwd the value for tbl_user.loginPwd
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.email
     *
     * @return the value of tbl_user.email
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.email
     *
     * @param email the value for tbl_user.email
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.expireTime
     *
     * @return the value of tbl_user.expireTime
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.expireTime
     *
     * @param expiretime the value for tbl_user.expireTime
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setExpiretime(String expiretime) {
        this.expiretime = expiretime == null ? null : expiretime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.lockStatus
     *
     * @return the value of tbl_user.lockStatus
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getLockstatus() {
        return lockstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.lockStatus
     *
     * @param lockstatus the value for tbl_user.lockStatus
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setLockstatus(String lockstatus) {
        this.lockstatus = lockstatus == null ? null : lockstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.allowIps
     *
     * @return the value of tbl_user.allowIps
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getAllowips() {
        return allowips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.allowIps
     *
     * @param allowips the value for tbl_user.allowIps
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setAllowips(String allowips) {
        this.allowips = allowips == null ? null : allowips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.createBy
     *
     * @return the value of tbl_user.createBy
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.createBy
     *
     * @param createby the value for tbl_user.createBy
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.createTime
     *
     * @return the value of tbl_user.createTime
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.createTime
     *
     * @param createtime the value for tbl_user.createTime
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.editBy
     *
     * @return the value of tbl_user.editBy
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getEditby() {
        return editby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.editBy
     *
     * @param editby the value for tbl_user.editBy
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setEditby(String editby) {
        this.editby = editby == null ? null : editby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.editTime
     *
     * @return the value of tbl_user.editTime
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public String getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.editTime
     *
     * @param edittime the value for tbl_user.editTime
     *
     * @mbggenerated Sat Aug 06 19:33:40 CST 2022
     */
    public void setEdittime(String edittime) {
        this.edittime = edittime == null ? null : edittime.trim();
    }
}